### ISSUE TITLE
Add link to docs on top nav

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster-cloud#4]
Would love to be able to navigate to the docs pages (and perhaps the GH repo) from Dagster Cloud. A few less bookmarks to worry about :)

**Comment by rexledesma** [comment]
Thanks for the feedback. Our future plan is to combine the open-source and cloud docs on one site, and make the experience of navigating between your Dagster Cloud instance + Dagster-related resources for development more streamlined.

Although this doesn't immediately solve your concerns, a [new version of the docs site](https://dagster-git-yuhan-docs-design-update-elementl.vercel.app/master/getting-started) is shipping tomorrow, which will have a link to the Dagster Cloud docs.

See this PR for more details: https://github.com/dagster-io/dagster/pull/7531.

**Comment by cbini** [comment]
this exists now - kick ass!
